import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One unified sidebar, like viem.sh: docs sections first, then the full API
// reference. Categories are collapsible but render expanded so every action
// is visible without clicking through.
const sidebars: SidebarsConfig = {
  docs: [
    'introduction',
    'getting-started',
    {
      type: 'category',
      label: 'Clients',
      collapsed: false,
      items: [
        'clients/public-client',
        'clients/wallet-client',
        'clients/test-client',
        'clients/transports',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/reading-chain-state',
        'guides/executing-transactions',
        'guides/working-with-records',
        'guides/transaction-lifecycle',
        'guides/contract-instances',
        'guides/devnode',
        'guides/agents',
        'guides/shield-swap',
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      collapsed: false,
      items: [
        'packages/overview',
        'packages/core',
        'packages/provable-sdk',
        'packages/wallet-adapter',
        'packages/react',
        'packages/shield-swap',
        'packages/codegen',
        'packages/devnode',
        'packages/leo',
        'packages/bridge',
      ],
    },
    {
      type: 'category',
      label: 'React',
      collapsed: false,
      items: [
        'react/overview',
        'react/veil-provider',
        'react/use-veil-wallet',
      ],
    },
    'api/transports',
    'api/types',
    {
      type: 'category',
      label: 'Public Actions',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Blocks',
          collapsed: false,
          items: [
            'api/public/getBlock',
            'api/public/getBlocks',
            'api/public/getBlockNumber',
            'api/public/getBlockHash',
            'api/public/getBlockHeightByHash',
            'api/public/getBlockSummary',
            'api/public/getBlockTransactions',
            'api/public/getBlockTransactionsByHash',
            'api/public/findBlockHash',
            'api/public/findBlockHeightByStateRoot',
          ],
        },
        {
          type: 'category',
          label: 'Transactions',
          collapsed: false,
          items: [
            'api/public/getTransaction',
            'api/public/getConfirmedTransaction',
            'api/public/getUnconfirmedTransaction',
            'api/public/getTransactionSummary',
            'api/public/getTransactionByTransition',
            'api/public/getTransitions',
            'api/public/getTransitionViewKeys',
            'api/public/findTransactionId',
            'api/public/findTransitionId',
          ],
        },
        {
          type: 'category',
          label: 'Programs',
          collapsed: false,
          items: [
            'api/public/getCode',
            'api/public/getProgramAddress',
            'api/public/getProgramIdByAddress',
            'api/public/getProgramByEdition',
            'api/public/getLatestEdition',
            'api/public/getDeploymentTransaction',
            'api/public/getDeploymentTransactionByEdition',
            'api/public/getOriginalDeploymentTransaction',
            'api/public/getAmendmentCount',
            'api/public/getAmendmentCountByEdition',
            'api/public/getAmendmentDeploymentTransaction',
            'api/public/getProgramCalls',
            'api/public/getProgramCallsPaginated',
          ],
        },
        {
          type: 'category',
          label: 'Mappings & Accounts',
          collapsed: false,
          items: [
            'api/public/readMapping',
            'api/public/readContract',
            'api/public/getMappingNames',
            'api/public/getBalance',
            'api/public/getTransactionsByAddress',
          ],
        },
        {
          type: 'category',
          label: 'Staking, Metrics & Supply',
          collapsed: false,
          items: [
            'api/public/getCommittee',
            'api/public/getDelegators',
            'api/public/getApy',
            'api/public/getValidatorApy',
            'api/public/getStakingEarnings',
            'api/public/getTransactionMetrics',
            'api/public/getProgramMetrics',
            'api/public/getProgramMetricsByRange',
            'api/public/getCirculatingSupply',
            'api/public/getTotalSupply',
            'api/public/getTvl',
          ],
        },
        {
          type: 'category',
          label: 'State Proofs & Tokens',
          collapsed: false,
          items: [
            'api/public/getStateRoot',
            'api/public/getStatePath',
            'api/public/getStatePaths',
            'api/public/getTokens',
            'api/public/getTokenDetails',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Wallet Actions',
      collapsed: false,
      items: [
        'api/wallet/writeContract',
        'api/wallet/executeContract',
        'api/wallet/simulateContract',
        'api/wallet/deployContract',
        'api/wallet/sendTransaction',
        'api/wallet/transfer',
        'api/wallet/signMessage',
        'api/wallet/decrypt',
        'api/wallet/requestRecords',
        'api/wallet/requestTransactionHistory',
        'api/wallet/transactionStatus',
        'api/wallet/getChainId',
        'api/wallet/switchChain',
      ],
    },
    {
      type: 'category',
      label: 'Test Actions',
      collapsed: false,
      items: [
        'api/test/advanceBlock',
        'api/test/getMappingKeysValues',
        'api/test/snapshot',
        'api/test/listSnapshots',
        'api/test/shutdown',
      ],
    },
    {
      type: 'category',
      label: 'Shield Swap',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'api/shield-swap' }],
    },
    {
      type: 'category',
      label: 'Provable SDK',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'api/provable-sdk' }],
    },
    {
      type: 'category',
      label: 'Devnode',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'api/devnode' }],
    },
    {
      type: 'category',
      label: 'Leo',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'api/leo' }],
    },
  ],
};

export default sidebars;
