/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/airdrop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /airdrop
         * @description Mints 1000 (×10^decimals) of every token registered in the DB to the given
         *     address by calling `<wrapper_program>::mint_public` on each. Because each
         *     token's admin is the treasury/deployer key, this never requires the treasury
         *     to hold a balance — it mints fresh supply.
         *
         *     Proving each token takes ~15-30s and the list can be long, so this returns
         *     immediately with `status: "running"` + a `job_id`. The mints run in a
         *     detached worker (capped concurrency, per-token timeout); poll
         *     `GET /airdrop/{job_id}` until `status == "complete"` to read per-token
         *     results.
         *
         *     Required env: `DEPLOYER_PRIVATE_KEY` (the treasury/admin of every token;
         *     `AIRDROP_PRIVATE_KEY` honored as a fallback), `RPC_URLS` (first entry used).
         */
        post: operations["airdrop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airdrop/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /airdrop/{job_id}
         * @description Returns the current state of a background airdrop job: `status`
         *     (`"running"` | `"complete"`), the expected `total`, and the per-token
         *     `results` collected so far.
         */
        get: operations["airdrop_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_balances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pool_debug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fee-tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_fee_tiers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_pools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{key}/ohlcv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pool_ohlcv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{key}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pool_24h_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{key}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pool_trades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_positions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_position"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["find_route"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/trading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /schema/trading
         * @description Returns the full list of on-chain trading, liquidity, and token operations
         *     with their input signatures. Clients can use this to build transaction
         *     payloads without hardcoding the Leo function signatures.
         */
        get: operations["list_trading_schemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/trading/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /schema/trading/{id}
         * @description Returns the input schema for a single operation (e.g. `swap`, `mint`, `swap_private`).
         */
        get: operations["get_trading_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/swaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_swaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/swaps/{swap_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_swap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tick-spacings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tick_spacings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tokens"];
        put?: never;
        post: operations["create_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Status of a background airdrop job. `status` is `"running"` until every token
         *     has resolved, then `"complete"`. `results` grows as each per-token mint lands,
         *     so a poller sees live progress (`results.len()` of `total`).
         */
        AirdropJob: {
            results: components["schemas"]["AirdropResult"][];
            status: string;
            total: number;
        };
        AirdropRequest: {
            /** @description Aleo address (`aleo1...`) to receive 1000 of each registered token. */
            address: string;
        };
        AirdropResult: {
            /** @description Base-unit amount (`1000 * 10^decimals`). */
            amount: string;
            error?: string | null;
            status: string;
            symbol: string;
            token_address: string;
            tx_id?: string | null;
            wrapper_program: string;
        };
        /**
         * @description Returned by `POST /airdrop` — the airdrop now runs in the background, so the
         *     caller gets a `job_id` to poll `GET /airdrop/{job_id}` with.
         */
        AirdropStartResult: {
            job_id: string;
            status: string;
        };
        AuthTokenPayload: {
            token: string;
        };
        AuthTokenResponseDoc: {
            data: components["schemas"]["AuthTokenPayload"];
        };
        BalanceListResponseDoc: {
            data: components["schemas"]["TokenBalanceDoc"][];
        };
        ChallengePayload: {
            message: string;
            nonce: string;
        };
        ChallengeRequestDoc: {
            address: string;
        };
        ChallengeResponseDoc: {
            data: components["schemas"]["ChallengePayload"];
        };
        CreateTokenRequestDoc: {
            /** @description Aleo field ID (e.g. `1234567890field`). */
            address: string;
            /** Format: int32 */
            decimals: number;
            name: string;
            symbol: string;
            /** @description Deployed ARC-20 wrapper program ID (e.g. `mtk_a1b2c3.aleo`). Optional. */
            wrapper_program?: string | null;
        };
        ErrorResponseDoc: {
            error: string;
        };
        FeeTierDoc: {
            fee: string;
            /** Format: int32 */
            tick_spacing: number;
        };
        FeeTierListResponseDoc: {
            data: components["schemas"]["FeeTierDoc"][];
        };
        /** @description Full schema for a single trading / liquidity operation on the Aleo AMM. */
        FunctionSchema: {
            /** @description One-line human summary. */
            description: string;
            /** @description Optional follow-up transactions that must be executed after this one. */
            follow_up?: string[];
            /** @description Function name on-chain. */
            function: string;
            /** @description Short identifier (`swap`, `mint`, `create_pool`, ...). */
            id: string;
            /** @description Ordered list of inputs — index in this array == positional argument index. */
            inputs: components["schemas"]["SchemaField"][];
            /** @description Aleo program ID the function lives on (e.g. `leo_amm.aleo`, `token_registry.aleo`). */
            program: string;
            /** @description `public` (clear inputs) or `private` (hidden inputs using records). */
            visibility: string;
        };
        OhlcvDoc: {
            bucket: string;
            close: string;
            high: string;
            low: string;
            open: string;
            volume: string;
        };
        OhlcvResponseDoc: {
            data: components["schemas"]["OhlcvDoc"][];
        };
        PaginationMeta: {
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        PoolDebugInfoDoc: {
            /** Format: int32 */
            active_tick?: number | null;
            liquidity?: string | null;
            pool_key: string;
            slot_raw?: string | null;
            sqrt_price?: string | null;
            tick_spacing?: string | null;
            tick_statuses: components["schemas"]["TickStatusDoc"][];
        };
        PoolDebugResponseDoc: {
            data: components["schemas"]["PoolDebugInfoDoc"];
        };
        PoolListResponseDoc: {
            data: components["schemas"]["PoolResponseDoc"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        PoolResponseDoc: components["schemas"]["PoolStateDoc"] & {
            token0_info?: null | components["schemas"]["TokenDoc"];
            token1_info?: null | components["schemas"]["TokenDoc"];
        };
        PoolStateDoc: {
            created_at: string;
            creator: string;
            enabled: boolean;
            fee: string;
            id: string;
            init_tx: string;
            key: string;
            token0: string;
            token1: string;
        };
        PoolStatsDoc: {
            /** Format: int32 */
            active_tick: number;
            id: string;
            liquidity: string;
            pool: string;
            price: string;
            price_reversed: string;
            /** Format: int32 */
            tick_spacing: number;
        };
        PoolTradeDoc: {
            amount0: string;
            amount1: string;
            executed_at: string;
            id: string;
            is_private: boolean;
            pool: string;
            trade_type: string;
            transaction: string;
            transaction_hash?: string | null;
            user: string;
        };
        PoolTradesResponseDoc: {
            data: components["schemas"]["PoolTradeDoc"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        PoolWithStatsDoc: components["schemas"]["PoolStateDoc"] & {
            stats?: null | components["schemas"]["PoolStatsDoc"];
            token0_info?: null | components["schemas"]["TokenDoc"];
            token1_info?: null | components["schemas"]["TokenDoc"];
        };
        PoolWithStatsResponseDoc: {
            data: components["schemas"]["PoolWithStatsDoc"];
        };
        PositionDoc: {
            amount0: string;
            amount1: string;
            created_at: string;
            id: string;
            is_burned: boolean;
            liquidity: string;
            pool: string;
            /** Format: int32 */
            tick_lower: number;
            /** Format: int32 */
            tick_upper: number;
            token_id: string;
            transaction: string;
            transaction_hash?: string | null;
            user: string;
        };
        PositionListResponseDoc: {
            data: components["schemas"]["PositionDoc"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        PositionResponseDoc: {
            data: components["schemas"]["PositionDoc"];
        };
        RouteHopDoc: {
            /** Format: int32 */
            active_tick?: number | null;
            fee: string;
            initialized_ticks: number[];
            liquidity?: string | null;
            pool_key: string;
            price?: string | null;
            sqrt_price_raw?: string | null;
            /** Format: int32 */
            tick_spacing?: number | null;
            token_in: string;
            token_out: string;
            zero_for_one: boolean;
        };
        RouteResponseDoc: {
            data: components["schemas"]["RouteResultDoc"];
        };
        RouteResultDoc: {
            estimated_amount_out?: string | null;
            hops: components["schemas"]["RouteHopDoc"][];
            token_in: string;
            token_out: string;
        };
        /** @description Describes a single input field of an on-chain function or struct. */
        SchemaField: {
            /** @description Human-readable explanation of the field. */
            description: string;
            /** @description For struct-typed inputs, the nested field list. */
            fields?: components["schemas"]["SchemaField"][] | null;
            /** @description Parameter/field name as used in the Leo/Aleo program. */
            name: string;
            /**
             * @description Aleo type: `field`, `u128`, `u64`, `u32`, `u16`, `u8`, `i128`, `i32`, `bool`, `address`,
             *     a struct name (e.g. `SwapRequest`), or `record` for Aleo records.
             */
            type: string;
            /** @description `public` or `private` — controls whether the value is revealed on-chain. */
            visibility: string;
        };
        SwapDoc: {
            amount_remaining: string;
            executed_at: string;
            hops: components["schemas"]["SwapHopDoc"][];
            id: string;
            input_amount: string;
            input_token: string;
            input_token_info?: null | components["schemas"]["TokenDoc"];
            /** Format: int64 */
            nonce: number;
            output_amount: string;
            output_token: string;
            output_token_info?: null | components["schemas"]["TokenDoc"];
            pool: string;
            recipient: string;
            swap_id: string;
            trade: string;
            transaction: string;
            user: string;
        };
        SwapHopDoc: {
            pool: string;
            zero_for_one: boolean;
        };
        SwapListResponseDoc: {
            data: components["schemas"]["SwapDoc"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        SwapResponseDoc: {
            data: components["schemas"]["SwapDoc"];
        };
        TickSpacingDoc: {
            /** Format: int32 */
            tick_spacing: number;
        };
        TickSpacingListResponseDoc: {
            data: components["schemas"]["TickSpacingDoc"][];
        };
        TickStatusDoc: {
            exists: boolean;
            raw_value?: string | null;
            /** Format: int32 */
            tick: number;
            tick_mapping_key: string;
        };
        TokenBalanceDoc: {
            /** @description Base-unit balance (no decimals applied). */
            balance: string;
            /** Format: int32 */
            decimals: number;
            name: string;
            symbol: string;
            token_address: string;
            token_id: string;
        };
        TokenDoc: {
            address: string;
            /** Format: int32 */
            decimals: number;
            id: string;
            image?: string | null;
            name: string;
            symbol: string;
            wrapper_program?: string | null;
        };
        TokenListResponseDoc: {
            data: components["schemas"]["TokenDoc"][];
        };
        TokenResponseDoc: {
            data: components["schemas"]["TokenDoc"];
        };
        TradingSchemaListResponse: {
            data: components["schemas"]["FunctionSchema"][];
        };
        TradingSchemaResponse: {
            data: components["schemas"]["FunctionSchema"];
        };
        VerifyRequestDoc: {
            address: string;
            signature: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    airdrop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AirdropRequest"];
            };
        };
        responses: {
            /** @description Airdrop job started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirdropStartResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
            /** @description Misconfigured server (missing env vars) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    airdrop_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id returned by POST /airdrop */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current airdrop job state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirdropJob"];
                };
            };
            /** @description Unknown job id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    challenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequestDoc"];
            };
        };
        responses: {
            /** @description Challenge nonce + message to sign */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponseDoc"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequestDoc"];
            };
        };
        responses: {
            /** @description JWT bearer token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponseDoc"];
                };
            };
            /** @description Invalid / expired signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    list_balances: {
        parameters: {
            query: {
                /** @description Aleo address to fetch balances for */
                user: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-token on-chain authorized balances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceListResponseDoc"];
                };
            };
        };
    };
    pool_debug: {
        parameters: {
            query: {
                /** @description Pool key */
                pool_key: string;
                /** @description Comma-separated list of tick values to verify */
                ticks?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw on-chain pool slot + optional tick statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolDebugResponseDoc"];
                };
            };
        };
    };
    list_fee_tiers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered fee tiers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeTierListResponseDoc"];
                };
            };
        };
    };
    list_pools: {
        parameters: {
            query?: {
                /** @description Page size (1-100) */
                limit?: number;
                /** @description Page offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated pools with token metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolListResponseDoc"];
                };
            };
        };
    };
    get_pool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description On-chain pool field key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pool state + stats + token metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolWithStatsResponseDoc"];
                };
            };
            /** @description Pool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    get_pool_ohlcv: {
        parameters: {
            query: {
                /** @description Candle bucket: 1m | 5m | 15m | 1h | 4h | 1d */
                granularity: string;
                /** @description Inclusive unix-second start */
                from: number;
                /** @description Exclusive unix-second end */
                to: number;
            };
            header?: never;
            path: {
                /** @description Pool key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OHLCV candles for the range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcvResponseDoc"];
                };
            };
            /** @description Invalid granularity */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    get_pool_24h_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pool key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rolling 24h price/volume summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    get_pool_trades: {
        parameters: {
            query?: {
                /** @description Page size (1-100) */
                limit?: number;
                /** @description Page offset */
                offset?: number;
                /** @description Filter: swap | mint | burn | collect */
                trade_type?: string;
            };
            header?: never;
            path: {
                /** @description Pool key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated trade history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolTradesResponseDoc"];
                };
            };
            /** @description Pool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    list_positions: {
        parameters: {
            query: {
                /** @description Aleo address whose positions to fetch */
                user: string;
                /** @description Page size (1-100) */
                limit?: number;
                /** @description Page offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated LP positions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionListResponseDoc"];
                };
            };
        };
    };
    get_position: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description On-chain position NFT token_id */
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Position details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionResponseDoc"];
                };
            };
            /** @description Position not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    find_route: {
        parameters: {
            query: {
                /** @description Input token ID */
                token_in: string;
                /** @description Output token ID */
                token_out: string;
                /** @description Optional input amount for output estimation */
                amount_in?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Best swap route (BFS, max 3 hops) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponseDoc"];
                };
            };
            /** @description No route between the given tokens */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    list_trading_schemas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all on-chain operation schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradingSchemaListResponse"];
                };
            };
        };
    };
    get_trading_schema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Operation ID (swap, swap_private, mint, create_pool, burn, collect, decrease_liquidity, swap_multi_hop, swap_multi_hop_private, claim_swap_output, claim_swap_output_private, register_token, mint_public, mint_private, transfer_public_to_private, add_fee_tier, add_tick_spacing, set_pool_enabled) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema for the requested operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradingSchemaResponse"];
                };
            };
            /** @description Unknown operation ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_swaps: {
        parameters: {
            query: {
                /** @description Aleo address whose swaps to fetch */
                user: string;
                /** @description Page size (1-100) */
                limit?: number;
                /** @description Page offset */
                offset?: number;
                /** @description Filter by on-chain pool key */
                pool?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated swap history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapListResponseDoc"];
                };
            };
        };
    };
    get_swap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description On-chain swap ID */
                swap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Swap details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapResponseDoc"];
                };
            };
            /** @description Swap not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
    list_tick_spacings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered tick spacings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickSpacingListResponseDoc"];
                };
            };
        };
    };
    list_tokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All registered tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenListResponseDoc"];
                };
            };
        };
    };
    create_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequestDoc"];
            };
        };
        responses: {
            /** @description Token stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDoc"];
                };
            };
        };
    };
    get_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token address (Aleo field ID) */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDoc"];
                };
            };
            /** @description Token not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDoc"];
                };
            };
        };
    };
}
