// Auto-generated by @veil/codegen from loyalty_token.aleo
// Do not edit manually.

import { getContract } from '@veil/core'
import type { RecordValue, FutureValue, PublicClient, WalletClient, ABI } from '@veil/core'

export const PROGRAM_ID = 'loyalty_token.aleo' as const

export interface LoyaltyCard {
  owner: string
  card_id: string
  points: bigint
  tier: bigint
  _record: RecordValue
}

export function toLoyaltyCard(record: RecordValue): LoyaltyCard {
  return {
    owner: record.owner,
    card_id: record.fields.card_id?.value as string ?? '',
    points: record.fields.points?.value as bigint ?? 0n,
    tier: record.fields.tier?.value as bigint ?? 0n,
    _record: record,
  }
}

export type ApproveUpgradeInputs = {
  checksum: bigint[]
}

export type ApproveUpgradeOutputs = FutureValue

export type MintCardInputs = {
  recipient: string
  initial_points: bigint
  nonce: string
}

export type MintCardOutputs = [LoyaltyCard, FutureValue]

export type AddPointsInputs = {
  card: LoyaltyCard | RecordValue | string
  points_earned: bigint
}

export type AddPointsOutputs = [LoyaltyCard, FutureValue]

export type CheckPointsInputs = {
  card: LoyaltyCard | RecordValue | string
}

export type CheckPointsOutputs = [LoyaltyCard, bigint]

export type TransferCardInputs = {
  card: LoyaltyCard | RecordValue | string
  new_owner: string
}

export type TransferCardOutputs = [LoyaltyCard, FutureValue]

export type SplitCardInputs = {
  card: LoyaltyCard | RecordValue | string
  points_to_keep: bigint
  nonce: string
}

export type SplitCardOutputs = [LoyaltyCard, LoyaltyCard, FutureValue]

export type SplitCardV2Inputs = {
  card: LoyaltyCard | RecordValue | string
  points_to_keep: bigint
}

export type SplitCardV2Outputs = [LoyaltyCard, LoyaltyCard, FutureValue]

export type SpendPointsInputs = {
  card: LoyaltyCard | RecordValue | string
  points_to_spend: bigint
}

export type SpendPointsOutputs = LoyaltyCard

export type CardExistsMappingKey = string
export type CardExistsMappingValue = boolean

export type TotalCardsMappingKey = string
export type TotalCardsMappingValue = bigint

export type TotalPointsIssuedMappingKey = string
export type TotalPointsIssuedMappingValue = bigint

export type ApprovedUpgradesMappingKey = string
export type ApprovedUpgradesMappingValue = boolean

/** The parsed ABI for loyalty_token.aleo. */
export const PROGRAM_ABI: ABI = {
  "program": "loyalty_token.aleo",
  "structs": [],
  "records": [
    {
      "path": [
        "LoyaltyCard"
      ],
      "fields": [
        {
          "name": "owner",
          "type": {
            "kind": "primitive",
            "primitive": "address"
          },
          "mode": "none"
        },
        {
          "name": "card_id",
          "type": {
            "kind": "primitive",
            "primitive": "field"
          },
          "mode": "none"
        },
        {
          "name": "points",
          "type": {
            "kind": "primitive",
            "primitive": "u64"
          },
          "mode": "none"
        },
        {
          "name": "tier",
          "type": {
            "kind": "primitive",
            "primitive": "u8"
          },
          "mode": "none"
        }
      ]
    }
  ],
  "mappings": [
    {
      "name": "card_exists",
      "key": {
        "kind": "primitive",
        "primitive": "field"
      },
      "value": {
        "kind": "primitive",
        "primitive": "boolean"
      }
    },
    {
      "name": "total_cards",
      "key": {
        "kind": "primitive",
        "primitive": "field"
      },
      "value": {
        "kind": "primitive",
        "primitive": "u64"
      }
    },
    {
      "name": "total_points_issued",
      "key": {
        "kind": "primitive",
        "primitive": "field"
      },
      "value": {
        "kind": "primitive",
        "primitive": "u64"
      }
    },
    {
      "name": "approved_upgrades",
      "key": {
        "kind": "primitive",
        "primitive": "field"
      },
      "value": {
        "kind": "primitive",
        "primitive": "boolean"
      }
    }
  ],
  "storageVariables": [],
  "functions": [
    {
      "name": "approve_upgrade",
      "isFinal": true,
      "inputs": [
        {
          "name": "checksum",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "array",
              "element": {
                "kind": "primitive",
                "primitive": "u8"
              },
              "length": 32
            }
          },
          "mode": "none"
        }
      ],
      "outputs": [
        {
          "type": {
            "kind": "future"
          },
          "mode": "none"
        }
      ]
    },
    {
      "name": "mint_card",
      "isFinal": true,
      "inputs": [
        {
          "name": "recipient",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "address"
            }
          },
          "mode": "none"
        },
        {
          "name": "initial_points",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "u64"
            }
          },
          "mode": "none"
        },
        {
          "name": "nonce",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "field"
            }
          },
          "mode": "none"
        }
      ],
      "outputs": [
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "type": {
            "kind": "future"
          },
          "mode": "none"
        }
      ]
    },
    {
      "name": "add_points",
      "isFinal": true,
      "inputs": [
        {
          "name": "card",
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "name": "points_earned",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "u64"
            }
          },
          "mode": "none"
        }
      ],
      "outputs": [
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "type": {
            "kind": "future"
          },
          "mode": "none"
        }
      ]
    },
    {
      "name": "check_points",
      "isFinal": false,
      "inputs": [
        {
          "name": "card",
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        }
      ],
      "outputs": [
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "u64"
            }
          },
          "mode": "none"
        }
      ]
    },
    {
      "name": "transfer_card",
      "isFinal": true,
      "inputs": [
        {
          "name": "card",
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "name": "new_owner",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "address"
            }
          },
          "mode": "none"
        }
      ],
      "outputs": [
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "type": {
            "kind": "future"
          },
          "mode": "none"
        }
      ]
    },
    {
      "name": "split_card",
      "isFinal": true,
      "inputs": [
        {
          "name": "card",
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "name": "points_to_keep",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "u64"
            }
          },
          "mode": "none"
        },
        {
          "name": "nonce",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "field"
            }
          },
          "mode": "none"
        }
      ],
      "outputs": [
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "type": {
            "kind": "future"
          },
          "mode": "none"
        }
      ]
    },
    {
      "name": "split_card_v2",
      "isFinal": true,
      "inputs": [
        {
          "name": "card",
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "name": "points_to_keep",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "u64"
            }
          },
          "mode": "none"
        }
      ],
      "outputs": [
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "type": {
            "kind": "future"
          },
          "mode": "none"
        }
      ]
    },
    {
      "name": "spend_points",
      "isFinal": false,
      "inputs": [
        {
          "name": "card",
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        },
        {
          "name": "points_to_spend",
          "type": {
            "kind": "plaintext",
            "type": {
              "kind": "primitive",
              "primitive": "u64"
            }
          },
          "mode": "none"
        }
      ],
      "outputs": [
        {
          "type": {
            "kind": "record",
            "path": [
              "LoyaltyCard"
            ],
            "program": "loyalty_token"
          },
          "mode": "none"
        }
      ]
    }
  ]
}

export interface LoyaltyTokenContract {
  program: string
  abi: ABI
  read: {
    card_exists: (params: { key: string }) => Promise<unknown>
    total_cards: (params: { key: string }) => Promise<unknown>
    total_points_issued: (params: { key: string }) => Promise<unknown>
    approved_upgrades: (params: { key: string }) => Promise<unknown>
  }
  write: {
    approve_upgrade: (params: { checksum: bigint[] } & { fee?: bigint }) => Promise<string>
    mint_card: (params: { recipient: string, initial_points: bigint, nonce: string } & { fee?: bigint }) => Promise<string>
    add_points: (params: { card: LoyaltyCard | RecordValue | string, points_earned: bigint } & { fee?: bigint }) => Promise<string>
    check_points: (params: { card: LoyaltyCard | RecordValue | string } & { fee?: bigint }) => Promise<string>
    transfer_card: (params: { card: LoyaltyCard | RecordValue | string, new_owner: string } & { fee?: bigint }) => Promise<string>
    split_card: (params: { card: LoyaltyCard | RecordValue | string, points_to_keep: bigint, nonce: string } & { fee?: bigint }) => Promise<string>
    split_card_v2: (params: { card: LoyaltyCard | RecordValue | string, points_to_keep: bigint } & { fee?: bigint }) => Promise<string>
    spend_points: (params: { card: LoyaltyCard | RecordValue | string, points_to_spend: bigint } & { fee?: bigint }) => Promise<string>
  }
  simulate: {
    approve_upgrade: (params: { checksum: bigint[] }) => Promise<FutureValue>
    mint_card: (params: { recipient: string, initial_points: bigint, nonce: string }) => Promise<[LoyaltyCard, FutureValue]>
    add_points: (params: { card: LoyaltyCard | RecordValue | string, points_earned: bigint }) => Promise<[LoyaltyCard, FutureValue]>
    check_points: (params: { card: LoyaltyCard | RecordValue | string }) => Promise<[LoyaltyCard, bigint]>
    transfer_card: (params: { card: LoyaltyCard | RecordValue | string, new_owner: string }) => Promise<[LoyaltyCard, FutureValue]>
    split_card: (params: { card: LoyaltyCard | RecordValue | string, points_to_keep: bigint, nonce: string }) => Promise<[LoyaltyCard, LoyaltyCard, FutureValue]>
    split_card_v2: (params: { card: LoyaltyCard | RecordValue | string, points_to_keep: bigint }) => Promise<[LoyaltyCard, LoyaltyCard, FutureValue]>
    spend_points: (params: { card: LoyaltyCard | RecordValue | string, points_to_spend: bigint }) => Promise<LoyaltyCard>
  }
  execute: {
    approve_upgrade: (params: { checksum: bigint[] } & { fee?: bigint }) => Promise<{ transactionId: string, result: FutureValue }>
    mint_card: (params: { recipient: string, initial_points: bigint, nonce: string } & { fee?: bigint }) => Promise<{ transactionId: string, result: [LoyaltyCard, FutureValue] }>
    add_points: (params: { card: LoyaltyCard | RecordValue | string, points_earned: bigint } & { fee?: bigint }) => Promise<{ transactionId: string, result: [LoyaltyCard, FutureValue] }>
    check_points: (params: { card: LoyaltyCard | RecordValue | string } & { fee?: bigint }) => Promise<{ transactionId: string, result: [LoyaltyCard, bigint] }>
    transfer_card: (params: { card: LoyaltyCard | RecordValue | string, new_owner: string } & { fee?: bigint }) => Promise<{ transactionId: string, result: [LoyaltyCard, FutureValue] }>
    split_card: (params: { card: LoyaltyCard | RecordValue | string, points_to_keep: bigint, nonce: string } & { fee?: bigint }) => Promise<{ transactionId: string, result: [LoyaltyCard, LoyaltyCard, FutureValue] }>
    split_card_v2: (params: { card: LoyaltyCard | RecordValue | string, points_to_keep: bigint } & { fee?: bigint }) => Promise<{ transactionId: string, result: [LoyaltyCard, LoyaltyCard, FutureValue] }>
    spend_points: (params: { card: LoyaltyCard | RecordValue | string, points_to_spend: bigint } & { fee?: bigint }) => Promise<{ transactionId: string, result: LoyaltyCard }>
  }
  fetchAbi: () => Promise<ABI>
}

export function createLoyaltyTokenContract(options: {
  publicClient?: PublicClient,
  walletClient?: WalletClient,
  programSource?: string,
  imports?: Record<string, string>,
}): LoyaltyTokenContract {
  if (!options.publicClient && !options.walletClient) throw new Error('At least one of publicClient or walletClient is required')
  const client = options.publicClient && options.walletClient
    ? { public: options.publicClient, wallet: options.walletClient }
    : (options.publicClient ?? options.walletClient)!
  const raw = getContract({ program: PROGRAM_ID, abi: PROGRAM_ABI, client, programSource: options.programSource, imports: options.imports })

  return {
    program: raw.program,
    abi: raw.abi as ABI,
    read: raw.read as LoyaltyTokenContract['read'],
    write: {
      approve_upgrade: (params: any) => {
        const { checksum, fee } = params
        return raw.write.approve_upgrade({ inputs: [checksum], fee })
      },
      mint_card: (params: any) => {
        const { recipient, initial_points, nonce, fee } = params
        return raw.write.mint_card({ inputs: [recipient, initial_points, nonce], fee })
      },
      add_points: (params: any) => {
        const { card, points_earned, fee } = params
        const _card = card?._record ?? card
        return raw.write.add_points({ inputs: [_card, points_earned], fee })
      },
      check_points: (params: any) => {
        const { card, fee } = params
        const _card = card?._record ?? card
        return raw.write.check_points({ inputs: [_card], fee })
      },
      transfer_card: (params: any) => {
        const { card, new_owner, fee } = params
        const _card = card?._record ?? card
        return raw.write.transfer_card({ inputs: [_card, new_owner], fee })
      },
      split_card: (params: any) => {
        const { card, points_to_keep, nonce, fee } = params
        const _card = card?._record ?? card
        return raw.write.split_card({ inputs: [_card, points_to_keep, nonce], fee })
      },
      split_card_v2: (params: any) => {
        const { card, points_to_keep, fee } = params
        const _card = card?._record ?? card
        return raw.write.split_card_v2({ inputs: [_card, points_to_keep], fee })
      },
      spend_points: (params: any) => {
        const { card, points_to_spend, fee } = params
        const _card = card?._record ?? card
        return raw.write.spend_points({ inputs: [_card, points_to_spend], fee })
      },
    },
    simulate: {
      approve_upgrade: async (params: any) => {
        const { checksum } = params
        const result = await raw.simulate.approve_upgrade({ inputs: [checksum] })
        return result.outputs[0] as unknown as FutureValue
      },
      mint_card: async (params: any) => {
        const { recipient, initial_points, nonce } = params
        const result = await raw.simulate.mint_card({ inputs: [recipient, initial_points, nonce] })
        return [toLoyaltyCard(result.outputs[0] as RecordValue), result.outputs[1] as unknown as FutureValue] as const
      },
      add_points: async (params: any) => {
        const { card, points_earned } = params
        const _card = card?._record ?? card
        const result = await raw.simulate.add_points({ inputs: [_card, points_earned] })
        return [toLoyaltyCard(result.outputs[0] as RecordValue), result.outputs[1] as unknown as FutureValue] as const
      },
      check_points: async (params: any) => {
        const { card } = params
        const _card = card?._record ?? card
        const result = await raw.simulate.check_points({ inputs: [_card] })
        return [toLoyaltyCard(result.outputs[0] as RecordValue), result.outputs[1] as unknown as bigint] as const
      },
      transfer_card: async (params: any) => {
        const { card, new_owner } = params
        const _card = card?._record ?? card
        const result = await raw.simulate.transfer_card({ inputs: [_card, new_owner] })
        return [toLoyaltyCard(result.outputs[0] as RecordValue), result.outputs[1] as unknown as FutureValue] as const
      },
      split_card: async (params: any) => {
        const { card, points_to_keep, nonce } = params
        const _card = card?._record ?? card
        const result = await raw.simulate.split_card({ inputs: [_card, points_to_keep, nonce] })
        return [toLoyaltyCard(result.outputs[0] as RecordValue), toLoyaltyCard(result.outputs[1] as RecordValue), result.outputs[2] as unknown as FutureValue] as const
      },
      split_card_v2: async (params: any) => {
        const { card, points_to_keep } = params
        const _card = card?._record ?? card
        const result = await raw.simulate.split_card_v2({ inputs: [_card, points_to_keep] })
        return [toLoyaltyCard(result.outputs[0] as RecordValue), toLoyaltyCard(result.outputs[1] as RecordValue), result.outputs[2] as unknown as FutureValue] as const
      },
      spend_points: async (params: any) => {
        const { card, points_to_spend } = params
        const _card = card?._record ?? card
        const result = await raw.simulate.spend_points({ inputs: [_card, points_to_spend] })
        return toLoyaltyCard(result.outputs[0] as RecordValue)
      },
    },
    execute: {
      approve_upgrade: async (params: any) => {
        const { checksum, fee } = params
        const result = await raw.execute.approve_upgrade({ inputs: [checksum], fee })
        return { transactionId: result.transactionId, result: result.outputs[0] as unknown as FutureValue }
      },
      mint_card: async (params: any) => {
        const { recipient, initial_points, nonce, fee } = params
        const result = await raw.execute.mint_card({ inputs: [recipient, initial_points, nonce], fee })
        return { transactionId: result.transactionId, result: [toLoyaltyCard(result.outputs[0] as RecordValue), result.outputs[1] as unknown as FutureValue] as const }
      },
      add_points: async (params: any) => {
        const { card, points_earned, fee } = params
        const _card = card?._record ?? card
        const result = await raw.execute.add_points({ inputs: [_card, points_earned], fee })
        return { transactionId: result.transactionId, result: [toLoyaltyCard(result.outputs[0] as RecordValue), result.outputs[1] as unknown as FutureValue] as const }
      },
      check_points: async (params: any) => {
        const { card, fee } = params
        const _card = card?._record ?? card
        const result = await raw.execute.check_points({ inputs: [_card], fee })
        return { transactionId: result.transactionId, result: [toLoyaltyCard(result.outputs[0] as RecordValue), result.outputs[1] as unknown as bigint] as const }
      },
      transfer_card: async (params: any) => {
        const { card, new_owner, fee } = params
        const _card = card?._record ?? card
        const result = await raw.execute.transfer_card({ inputs: [_card, new_owner], fee })
        return { transactionId: result.transactionId, result: [toLoyaltyCard(result.outputs[0] as RecordValue), result.outputs[1] as unknown as FutureValue] as const }
      },
      split_card: async (params: any) => {
        const { card, points_to_keep, nonce, fee } = params
        const _card = card?._record ?? card
        const result = await raw.execute.split_card({ inputs: [_card, points_to_keep, nonce], fee })
        return { transactionId: result.transactionId, result: [toLoyaltyCard(result.outputs[0] as RecordValue), toLoyaltyCard(result.outputs[1] as RecordValue), result.outputs[2] as unknown as FutureValue] as const }
      },
      split_card_v2: async (params: any) => {
        const { card, points_to_keep, fee } = params
        const _card = card?._record ?? card
        const result = await raw.execute.split_card_v2({ inputs: [_card, points_to_keep], fee })
        return { transactionId: result.transactionId, result: [toLoyaltyCard(result.outputs[0] as RecordValue), toLoyaltyCard(result.outputs[1] as RecordValue), result.outputs[2] as unknown as FutureValue] as const }
      },
      spend_points: async (params: any) => {
        const { card, points_to_spend, fee } = params
        const _card = card?._record ?? card
        const result = await raw.execute.spend_points({ inputs: [_card, points_to_spend], fee })
        return { transactionId: result.transactionId, result: toLoyaltyCard(result.outputs[0] as RecordValue) }
      },
    },
    fetchAbi: raw.fetchAbi as unknown as LoyaltyTokenContract['fetchAbi'],
  }
}
