// Code generator — reads a parsed ABI and produces TypeScript source code.

import type { ABI, RecordDef, StructDef, AbiFunction, Mapping, StorageVariable, StorageType } from '@veil/core'
import type { Plaintext, Primitive } from '@veil/core'

// ── Public API ────────────────────────────────────────────────────────

/**
 * Options for {@link generate}.
 *
 * @property abi Parsed ABI the bindings are generated from — it supplies the
 *   structs, records, functions, mappings, and storage variables to emit.
 * @property coreImport Import path emitted for `@veil/core` types. Defaults to
 *   `'@veil/core'`. Override when the generated file resolves core through an
 *   alias or a relative path (e.g. inside the monorepo).
 * @property programId Program id to stamp into the emitted `PROGRAM_ID` and
 *   the generated contract factory. Defaults to the ABI's own `program`.
 *   Override when the bindings' shape is taken from one deployment's ABI but
 *   they target another — e.g. when a newer program version's ABI is the only
 *   one current tooling can parse, yet the live deployment (identical shape)
 *   has a different id.
 */
export interface GenerateOptions {
  abi: ABI
  coreImport?: string
  programId?: string
}

/**
 * Generates TypeScript source code from an Aleo program ABI.
 *
 * Produces:
 * - Struct interfaces
 * - Record interfaces with correctly typed fields
 * - Record mapper functions (RecordValue → typed interface)
 * - Function input and output types
 * - Mapping key/value types
 * - Storage variable types
 */
export function generate(options: GenerateOptions): string {
  const { abi, coreImport = '@veil/core', programId = abi.program } = options
  const lines: string[] = []

  // Header
  lines.push(`// Auto-generated by @veil/codegen from ${abi.program}`)
  lines.push(`// Do not edit manually.`)
  lines.push('')
  lines.push(`import { getContract } from '${coreImport}'`)
  lines.push(`import type { RecordValue, FutureValue, PublicClient, WalletClient, ABI, InputRequest, PlaintextValue } from '${coreImport}'`)
  lines.push('')

  // Program ID constant — the program these bindings target (see programId option).
  lines.push(`export const PROGRAM_ID = '${programId}' as const`)
  lines.push('')

  // Decoder helper: literal types (field/group/scalar) may arrive from runtime
  // parsers as bigint (suffix stripped) or as the canonical suffixed string.
  // Normalize to the canonical string form so decoded objects match the
  // generated interfaces at runtime.
  lines.push(`function litStr(v: PlaintextValue | undefined, suffix: string): string {`)
  lines.push(`  if (typeof v === 'bigint') return \`\${v}\${suffix}\``)
  lines.push(`  if (typeof v === 'string') return v`)
  lines.push(`  if (v == null) return ''`)
  lines.push(`  // Fail fast: a struct/array/boolean value in a literal slot means the ABI`)
  lines.push(`  // or an upstream parser is wrong — never coerce it into corrupt data.`)
  lines.push(`  throw new Error(\`Expected \${suffix} literal, got \${typeof v}\`)`)
  lines.push(`}`)
  lines.push('')

  // Structs
  for (const struct of abi.structs) {
    lines.push(...generateStructInterface(struct))
    lines.push('')
    lines.push(...generateStructMapper(struct))
    lines.push('')
  }

  // Records
  for (const record of abi.records) {
    lines.push(...generateRecordInterface(record))
    lines.push('')
    lines.push(...generateRecordMapper(record))
    lines.push('')
  }

  // Function input + output types
  for (const fn of abi.functions) {
    lines.push(...generateFunctionInputType(fn, abi))
    lines.push('')
    lines.push(...generateFunctionOutputType(fn, abi))
    lines.push('')
  }

  // Mapping types
  for (const mapping of abi.mappings) {
    lines.push(...generateMappingType(mapping))
    lines.push('')
  }

  // Storage variable types
  for (const sv of abi.storageVariables) {
    lines.push(...generateStorageVariableType(sv))
    lines.push('')
  }

  // ABI constant + contract factory
  lines.push(...generateAbiConstant(abi))
  lines.push('')
  lines.push(...generateContractFactory(abi))
  lines.push('')

  return lines.join('\n')
}

// ── Struct generation ─────────────────────────────────────────────────

function generateStructInterface(struct: StructDef): string[] {
  const name = struct.path[struct.path.length - 1] ?? 'UnknownStruct'
  const lines: string[] = []

  lines.push(`export interface ${name} {`)

  for (const field of struct.fields) {
    const tsType = plaintextToTsType(field.type)
    lines.push(`  ${field.name}: ${tsType}`)
  }

  lines.push(`}`)
  return lines
}

// ── Record generation ─────────────────────────────────────────────────

function generateRecordInterface(record: RecordDef): string[] {
  const name = recordName(record)
  const lines: string[] = []

  lines.push(`export interface ${name} {`)
  lines.push(`  owner: string`)

  for (const field of record.fields) {
    if (field.name === 'owner') continue
    const tsType = plaintextToTsType(field.type)
    lines.push(`  ${field.name}: ${tsType}`)
  }

  // Carry the underlying RecordValue so typed records can be passed back as inputs
  lines.push(`  _record: RecordValue`)
  lines.push(`}`)
  return lines
}

// Emit the `field: <converted value>` lines shared by record and struct mappers.
// `varName` is the mapper's parameter name (the value being decoded); `container`
// names the enclosing type for error messages.
function mapperFieldLines(
  fields: readonly { name: string; type: Plaintext }[],
  container: string,
  varName: string,
): string[] {
  const lines: string[] = []
  for (const field of fields) {
    if (field.name === 'owner') continue
    // Struct-typed fields: the raw PlaintextValue is a StructValue at runtime.
    // Cast through unknown to the generated struct interface so the return type
    // is correct. A missing field falls back to an empty object cast the same way.
    if (field.type.kind === 'struct') {
      const structName = field.type.path.at(-1)
      if (!structName) {
        throw new Error(
          `Malformed ABI: struct field "${field.name}" in "${container}" has an empty type path. ` +
          `Cannot derive struct name for code generation.`
        )
      }
      lines.push(`    ${field.name}: ${varName}.fields.${field.name}?.value as unknown as ${structName} ?? {} as unknown as ${structName},`)
    } else {
      const rawAccess = `${varName}.fields.${field.name}?.value`
      const expr = plaintextFieldExpr(rawAccess, field.type)
      lines.push(`    ${field.name}: ${expr} ?? ${plaintextDefault(field.type)},`)
    }
  }
  return lines
}

function generateRecordMapper(record: RecordDef): string[] {
  const name = recordName(record)
  const lines: string[] = []

  lines.push(`export function to${name}(record: RecordValue): ${name} {`)
  lines.push(`  return {`)
  lines.push(`    owner: record.owner,`)
  lines.push(...mapperFieldLines(record.fields, name, 'record'))
  lines.push(`    _record: record,`)
  lines.push(`  }`)
  lines.push(`}`)
  return lines
}

// Decoder for a struct (e.g. a mapping value like PoolState/Slot). Same per-field
// width conversions as records, without the record-only `owner`/`_record` fields.
function generateStructMapper(struct: StructDef): string[] {
  const name = struct.path[struct.path.length - 1] ?? 'UnknownStruct'
  const lines: string[] = []

  lines.push(`export function to${name}(value: RecordValue): ${name} {`)
  lines.push(`  return {`)
  lines.push(...mapperFieldLines(struct.fields, name, 'value'))
  lines.push(`  }`)
  lines.push(`}`)
  return lines
}

// ── Function input generation ─────────────────────────────────────────

function generateFunctionInputType(fn: AbiFunction, abi: ABI): string[] {
  const typeName = pascalCase(fn.name) + 'Inputs'
  const lines: string[] = []

  lines.push(`export type ${typeName} = {`)

  for (const input of fn.inputs) {
    const name = input.name ?? `arg${fn.inputs.indexOf(input)}`

    // Every input slot also accepts an InputRequest — a privacy-preserving
    // wallet fulfils it (address injection, record selection, derived value).
    if (input.type.kind === 'plaintext') {
      const tsType = plaintextToTsType(input.type.type)
      lines.push(`  ${name}: ${tsType} | InputRequest`)
    } else if (input.type.kind === 'record') {
      const recName = input.type.path[input.type.path.length - 1] ?? 'RecordValue'
      const isLocal = !input.type.program || input.type.program.replace(/\.aleo$/, '') === abi.program.replace(/\.aleo$/, '')
      lines.push(`  ${name}: ${isLocal ? recName : 'RecordValue'} | RecordValue | string | InputRequest`)
    } else if (input.type.kind === 'dynamicRecord') {
      lines.push(`  ${name}: RecordValue | string | InputRequest`)
    }
  }

  lines.push(`}`)
  return lines
}

// ── Function output generation ────────────────────────────────────────

function generateFunctionOutputType(fn: AbiFunction, abi: ABI): string[] {
  const typeName = pascalCase(fn.name) + 'Outputs'
  const lines: string[] = []

  if (fn.outputs.length === 0) {
    lines.push(`export type ${typeName} = void`)
    return lines
  }

  if (fn.outputs.length === 1) {
    const tsType = outputToTsType(fn.outputs[0].type, abi)
    lines.push(`export type ${typeName} = ${tsType}`)
    return lines
  }

  const typeElements = fn.outputs.map((output) => outputToTsType(output.type, abi))
  lines.push(`export type ${typeName} = [${typeElements.join(', ')}]`)
  return lines
}

function outputToTsType(output: AbiFunction['outputs'][number]['type'], abi: ABI): string {
  if (output.kind === 'plaintext') {
    return plaintextToTsType(output.type)
  } else if (output.kind === 'record') {
    const recName = output.path[output.path.length - 1] ?? 'RecordValue'
    const isLocal = !output.program || output.program.replace(/\.aleo$/, '') === abi.program.replace(/\.aleo$/, '')
    return isLocal ? recName : 'RecordValue'
  } else if (output.kind === 'dynamicRecord') {
    return 'RecordValue'
  } else if (output.kind === 'future' || output.kind === 'dynamicFuture') {
    return 'FutureValue'
  }
  return 'unknown'
}

// ── Mapping generation ────────────────────────────────────────────────

function generateMappingType(mapping: Mapping): string[] {
  const name = pascalCase(mapping.name)
  const keyType = plaintextToTsType(mapping.key)
  const valueType = plaintextToTsType(mapping.value)

  return [
    `export type ${name}MappingKey = ${keyType}`,
    `export type ${name}MappingValue = ${valueType}`,
  ]
}

// ── Storage variable generation ───────────────────────────────────────

function generateStorageVariableType(sv: StorageVariable): string[] {
  const name = pascalCase(sv.name)
  const tsType = storageTypeToTs(sv.type)

  return [`export type ${name}StorageType = ${tsType}`]
}

function storageTypeToTs(st: StorageType): string {
  if (st.kind === 'plaintext') {
    return plaintextToTsType(st.type)
  } else if (st.kind === 'vector') {
    return `${storageTypeToTs(st.element)}[]`
  }
  return 'unknown'
}

// ── Type mapping helpers ──────────────────────────────────────────────

/**
 * Returns true for integer primitives that fit safely in a JS number (≤ 32-bit).
 *
 * u8/u16/u32 and i8/i16/i32 are typed as `number`; u64/u128 and i64/i128 require
 * `bigint` to avoid precision loss. This predicate is the single source of truth
 * for that boundary — all three type-mapping helpers delegate to it so that adding
 * a new width requires changing only this function.
 */
function isSmallInt(p: Primitive): boolean {
  return p === 'u8' || p === 'u16' || p === 'u32' || p === 'i8' || p === 'i16' || p === 'i32'
}

function plaintextToTsType(pt: Plaintext): string {
  switch (pt.kind) {
    case 'primitive':
      return primitiveToTsType(pt.primitive)
    case 'array':
      return `${plaintextToTsType(pt.element)}[]`
    case 'struct':
      return pt.path[pt.path.length - 1] ?? 'unknown'
    case 'optional':
      return `${plaintextToTsType(pt.inner)} | undefined`
    default:
      return 'unknown'
  }
}

function primitiveToTsType(p: Primitive): string {
  if (isSmallInt(p)) return 'number'
  switch (p) {
    case 'address':
    case 'field':
    case 'group':
    case 'scalar':
    case 'signature':
    case 'identifier':
      return 'string'
    case 'boolean':
      return 'boolean'
    // 64-bit and wider: must be bigint to avoid precision loss
    case 'u64':
    case 'u128':
    case 'i64':
    case 'i128':
      return 'bigint'
    default:
      return 'unknown'
  }
}

/**
 * Builds the full typed expression for a primitive record field access.
 *
 * The raw value stored in RecordFieldValue is always a bigint for all integer
 * widths (parsed by core's parseValue). For u8/u16/u32 and i8/i16/i32 fields
 * (typed as `number`), we wrap with Number() to convert at runtime. For u64+
 * (typed as `bigint`), we cast directly. For non-primitive types (array,
 * optional) the raw access is returned unchanged — those fall through to the
 * caller's existing handling.
 *
 * @param rawAccess - Expression yielding the raw PlaintextValue, e.g. `record.fields.x?.value`
 */
function plaintextFieldExpr(rawAccess: string, pt: Plaintext): string {
  // TODO(follow-up): non-primitive record fields other than struct (i.e. `array`,
  // `optional`) are NOT yet handled and fall through to the raw expression.
  // This is a known gap — ABIs containing such fields will produce non-compiling
  // output. Implement `array` and `optional` handling before using codegen with
  // such ABIs.
  if (pt.kind !== 'primitive') return rawAccess
  const p = pt.primitive
  // Small integers stored as bigint at runtime, exposed as number in the interface.
  // The ?? 0n guard is inside the Number() call: Number(undefined) = NaN, and
  // NaN ?? 0 does NOT trigger (?? only catches null/undefined). Guarding before
  // Number() ensures a missing field correctly defaults to 0.
  if (isSmallInt(p)) return `Number((${rawAccess} ?? 0n) as bigint)`
  switch (p) {
    // Wide integers stay bigint end-to-end.
    case 'u64':
    case 'u128':
    case 'i64':
    case 'i128':
      return `${rawAccess} as bigint`
    // Literal types with a suffix: runtime parsers may deliver these as bigint
    // (suffix stripped) or as the canonical suffixed string — normalize to the
    // canonical string form (e.g. 123n → "123field").
    case 'field':
    case 'group':
    case 'scalar':
      return `litStr(${rawAccess}, '${p}')`
    case 'address':
    case 'signature':
    case 'identifier':
      return `${rawAccess} as string`
    case 'boolean':
      return `${rawAccess} as boolean`
    default:
      return rawAccess
  }
}

function plaintextDefault(pt: Plaintext): string {
  // TODO(follow-up): see plaintextFieldExpr for the known array/optional gap.
  // Non-primitive record fields fall through to "''" (empty string default).
  if (pt.kind !== 'primitive') return "''"
  if (isSmallInt(pt.primitive)) return '0'
  switch (pt.primitive) {
    case 'boolean':
      return 'false'
    // Wide integers — bigint default
    case 'u64': case 'u128': case 'i64': case 'i128':
      return '0n'
    case 'field': case 'group': case 'scalar':
      return "''"
    case 'address': case 'signature': case 'identifier':
      return "''"
    default:
      return "''"
  }
}

// ── ABI constant + contract factory ───────────────────────────────────

function generateAbiConstant(abi: ABI): string[] {
  // Embed the already-parsed ABI as a typed constant.
  // This avoids a round-trip through parseAbi at runtime.
  return [
    `/** The parsed ABI for ${abi.program}. */`,
    `export const PROGRAM_ABI: ABI = ${JSON.stringify(abi, null, 2)}`,
  ]
}

/** Generate named param type string for a function's inputs */
function namedParamsType(fn: AbiFunction, abi: ABI): string {
  if (fn.inputs.length === 0) return '{}'
  const params = fn.inputs.map((input) => {
    const name = input.name ?? `arg${fn.inputs.indexOf(input)}`
    let tsType: string
    if (input.type.kind === 'plaintext') {
      tsType = plaintextToTsType(input.type.type)
    } else if (input.type.kind === 'record') {
      const recName = input.type.path[input.type.path.length - 1] ?? 'RecordValue'
      const isLocal = !input.type.program || input.type.program.replace(/\.aleo$/, '') === abi.program.replace(/\.aleo$/, '')
      tsType = isLocal ? `${recName} | RecordValue | string` : 'RecordValue | string'
    } else {
      tsType = 'RecordValue | string'
    }
    // Also accept an InputRequest in every slot (wallet-fulfilled input).
    return `${name}: ${tsType} | InputRequest`
  })
  return `{ ${params.join(', ')} }`
}

/** Generate the typed return type for simulate */
function simulateReturnType(fn: AbiFunction, abi: ABI): string {
  if (fn.outputs.length === 0) return 'void'
  if (fn.outputs.length === 1) return outputToTsType(fn.outputs[0].type, abi)
  return `[${fn.outputs.map((o) => outputToTsType(o.type, abi)).join(', ')}]`
}

/** Generate the typed return type for execute (includes transactionId) */
function executeReturnType(fn: AbiFunction, abi: ABI): string {
  const simType = simulateReturnType(fn, abi)
  if (simType === 'void') return '{ transactionId: string }'
  return `{ transactionId: string, result: ${simType} }`
}

/** Generate the input names array for converting named params to positional */
function inputNames(fn: AbiFunction): string[] {
  return fn.inputs.map((input, i) => input.name ?? `arg${i}`)
}

/**
 * For record inputs, generate resolution lines that extract _record from typed records.
 * Returns { resolveLines: string[], resolvedNames: string[] }.
 * resolvedNames replaces record input names with their resolved versions.
 */
function resolveRecordInputs(fn: AbiFunction): { resolveLines: string[], resolvedNames: string[] } {
  const resolveLines: string[] = []
  const resolvedNames: string[] = []

  for (let i = 0; i < fn.inputs.length; i++) {
    const input = fn.inputs[i]
    const name = input.name ?? `arg${i}`

    if (input.type.kind === 'record' || input.type.kind === 'dynamicRecord') {
      resolveLines.push(`        const _${name} = ${name}?._record ?? ${name}`)
      resolvedNames.push(`_${name}`)
    } else {
      resolvedNames.push(name)
    }
  }

  return { resolveLines, resolvedNames }
}

/** Generate output mapper expression for a single output at index i */
function outputMapperExpr(output: AbiFunction['outputs'][number], i: number, abi: ABI): string {
  if (output.type.kind === 'record') {
    const recName = output.type.path[output.type.path.length - 1] ?? ''
    const isLocal = !output.type.program || output.type.program.replace(/\.aleo$/, '') === abi.program.replace(/\.aleo$/, '')
    // Double-cast through unknown: result.outputs[i] is ParsedOutput | undefined under
    // noUncheckedIndexedAccess. The cast to unknown then to RecordValue is intentional —
    // the ABI guarantees this output is a record at this position.
    if (isLocal && recName) {
      return `to${recName}(result.outputs[${i}] as unknown as RecordValue)`
    }
    return `result.outputs[${i}] as unknown as RecordValue`
  }
  if (output.type.kind === 'plaintext') {
    return `result.outputs[${i}] as unknown as ${plaintextToTsType(output.type.type)}`
  }
  if (output.type.kind === 'future' || output.type.kind === 'dynamicFuture') {
    return `result.outputs[${i}] as unknown as FutureValue`
  }
  return `result.outputs[${i}]`
}

function generateContractFactory(abi: ABI): string[] {
  const programName = abi.program
  const factoryName = pascalCase(programName.replace('.aleo', ''))
  const lines: string[] = []

  // Generate typed interface with named params and typed returns
  lines.push(`export interface ${factoryName}Contract {`)
  lines.push(`  program: string`)
  lines.push(`  abi: ABI`)

  // read methods
  if (abi.mappings.length > 0) {
    lines.push(`  read: {`)
    for (const mapping of abi.mappings) {
      const keyType = plaintextToTsType(mapping.key)
      lines.push(`    ${mapping.name}: (params: { key: ${keyType} }) => Promise<unknown>`)
    }
    lines.push(`  }`)
  } else {
    lines.push(`  read: Record<string, (params: { key: string }) => Promise<unknown>>`)
  }

  // write methods — named params, returns tx ID
  if (abi.functions.length > 0) {
    lines.push(`  write: {`)
    for (const fn of abi.functions) {
      const params = namedParamsType(fn, abi)
      lines.push(`    ${fn.name}: (params: ${params}) => Promise<string>`)
    }
    lines.push(`  }`)
  }

  // simulate methods — named params, typed return
  if (abi.functions.length > 0) {
    lines.push(`  simulate: {`)
    for (const fn of abi.functions) {
      const params = namedParamsType(fn, abi)
      const retType = simulateReturnType(fn, abi)
      lines.push(`    ${fn.name}: (params: ${params}) => Promise<${retType}>`)
    }
    lines.push(`  }`)
  }

  // execute methods — named params, typed return + transactionId.
  // Fee belongs in proving config, not per-call params — do not add fee here.
  if (abi.functions.length > 0) {
    lines.push(`  execute: {`)
    for (const fn of abi.functions) {
      const params = namedParamsType(fn, abi)
      const retType = executeReturnType(fn, abi)
      lines.push(`    ${fn.name}: (params: ${params}) => Promise<${retType}>`)
    }
    lines.push(`  }`)
  }

  lines.push(`  fetchAbi: () => Promise<ABI>`)
  lines.push(`}`)
  lines.push('')

  // Generate factory with wrapper methods
  lines.push(`export function create${factoryName}Contract(options: {`)
  lines.push(`  publicClient?: PublicClient,`)
  lines.push(`  walletClient?: WalletClient,`)
  lines.push(`  programSource?: string,`)
  lines.push(`  imports?: Record<string, string>,`)
  lines.push(`}): ${factoryName}Contract {`)
  lines.push(`  if (!options.publicClient && !options.walletClient) throw new Error('At least one of publicClient or walletClient is required')`)
  lines.push(`  const client = options.publicClient && options.walletClient`)
  lines.push(`    ? { public: options.publicClient, wallet: options.walletClient }`)
  lines.push(`    : (options.publicClient ?? options.walletClient)!`)
  lines.push(`  const raw = getContract({ program: PROGRAM_ID, abi: PROGRAM_ABI, client, programSource: options.programSource, imports: options.imports })`)
  // Proxy method access is typed as Record<string, fn> whose properties are
  // T | undefined under noUncheckedIndexedAccess. Cast to any for the internal
  // wrappers — the typed factory interface above is what consumers see.
  lines.push(`  const _raw = raw as any`)
  lines.push('')
  lines.push(`  return {`)
  lines.push(`    program: raw.program,`)
  lines.push(`    abi: raw.abi as ABI,`)
  lines.push(`    read: _raw.read as ${factoryName}Contract['read'],`)

  // write wrappers — convert named params to positional inputs
  if (abi.functions.length > 0) {
    lines.push(`    write: {`)
    for (const fn of abi.functions) {
      const names = inputNames(fn)
      const { resolveLines, resolvedNames } = resolveRecordInputs(fn)
      lines.push(`      ${fn.name}: (params: any) => {`)
      if (names.length > 0) lines.push(`        const { ${names.join(', ')} } = params`)
      for (const line of resolveLines) lines.push(line)
      lines.push(`        return _raw.write.${fn.name}({ inputs: [${resolvedNames.join(', ')}] })`)
      lines.push(`      },`)
    }
    lines.push(`    },`)
  }

  // simulate wrappers — convert named params to positional, map outputs to typed returns
  if (abi.functions.length > 0) {
    lines.push(`    simulate: {`)
    for (const fn of abi.functions) {
      const names = inputNames(fn)
      const { resolveLines, resolvedNames } = resolveRecordInputs(fn)
      lines.push(`      ${fn.name}: async (params: any) => {`)
      if (names.length > 0) lines.push(`        const { ${names.join(', ')} } = params`)
      for (const line of resolveLines) lines.push(line)

      if (fn.outputs.length === 0) {
        lines.push(`        await _raw.simulate.${fn.name}({ inputs: [${resolvedNames.join(', ')}] })`)
      } else {
        lines.push(`        const result = await _raw.simulate.${fn.name}({ inputs: [${resolvedNames.join(', ')}] })`)
      }

      if (fn.outputs.length === 0) {
        // void return
      } else if (fn.outputs.length === 1) {
        lines.push(`        return ${outputMapperExpr(fn.outputs[0], 0, abi)}`)
      } else {
        const mappers = fn.outputs.map((o, i) => outputMapperExpr(o, i, abi))
        lines.push(`        return [${mappers.join(', ')}] as const`)
      }

      lines.push(`      },`)
    }
    lines.push(`    },`)
  }

  // execute wrappers — same as simulate but includes transactionId
  if (abi.functions.length > 0) {
    lines.push(`    execute: {`)
    for (const fn of abi.functions) {
      const names = inputNames(fn)
      const { resolveLines, resolvedNames } = resolveRecordInputs(fn)
      lines.push(`      ${fn.name}: async (params: any) => {`)
      if (names.length > 0) lines.push(`        const { ${names.join(', ')} } = params`)
      for (const line of resolveLines) lines.push(line)
      lines.push(`        const result = await _raw.execute.${fn.name}({ inputs: [${resolvedNames.join(', ')}] })`)

      if (fn.outputs.length === 0) {
        lines.push(`        return { transactionId: result.transactionId }`)
      } else if (fn.outputs.length === 1) {
        lines.push(`        return { transactionId: result.transactionId, result: ${outputMapperExpr(fn.outputs[0], 0, abi)} }`)
      } else {
        const mappers = fn.outputs.map((o, i) => outputMapperExpr(o, i, abi))
        lines.push(`        return { transactionId: result.transactionId, result: [${mappers.join(', ')}] as const }`)
      }

      lines.push(`      },`)
    }
    lines.push(`    },`)
  }

  lines.push(`    fetchAbi: _raw.fetchAbi as unknown as ${factoryName}Contract['fetchAbi'],`)
  lines.push(`  }`)
  lines.push(`}`)

  return lines
}

// ── Utility ───────────────────────────────────────────────────────────

function recordName(record: RecordDef): string {
  return record.path[record.path.length - 1] ?? 'UnknownRecord'
}

function pascalCase(s: string): string {
  return s
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}
