// Code generator — reads a parsed ABI and produces TypeScript source code.

import type { ABI, RecordDef, StructDef, AbiFunction, Mapping, StorageVariable, StorageType } from '@veil/core'
import type { Plaintext, Primitive } from '@veil/core'

// ── Public API ────────────────────────────────────────────────────────

export interface GenerateOptions {
  /** The parsed ABI to generate from */
  abi: ABI
  /** Import path for @veil/core types (default: '@veil/core') */
  coreImport?: string
}

/**
 * Generates TypeScript source code from an Aleo program ABI.
 *
 * Produces:
 * - Struct interfaces
 * - Record interfaces with correctly typed fields
 * - Record mapper functions (RecordValue → typed interface)
 * - Function input and output types
 * - Mapping key/value types
 * - Storage variable types
 */
export function generate(options: GenerateOptions): string {
  const { abi, coreImport = '@veil/core' } = options
  const lines: string[] = []

  // Header
  lines.push(`// Auto-generated by @veil/codegen from ${abi.program}`)
  lines.push(`// Do not edit manually.`)
  lines.push('')
  lines.push(`import { getContract } from '${coreImport}'`)
  lines.push(`import type { RecordValue, PublicClient, WalletClient, ContractInstance, ABI } from '${coreImport}'`)
  lines.push(`import type { RawSimulateResult, RawExecuteResult } from '${coreImport}'`)
  lines.push('')

  // Program ID constant
  lines.push(`export const PROGRAM_ID = '${abi.program}' as const`)
  lines.push('')

  // Structs
  for (const struct of abi.structs) {
    lines.push(...generateStructInterface(struct))
    lines.push('')
  }

  // Records
  for (const record of abi.records) {
    lines.push(...generateRecordInterface(record))
    lines.push('')
    lines.push(...generateRecordMapper(record))
    lines.push('')
  }

  // Function input + output types
  for (const fn of abi.functions) {
    lines.push(...generateFunctionInputType(fn, abi))
    lines.push('')
    lines.push(...generateFunctionOutputType(fn, abi))
    lines.push('')
  }

  // Mapping types
  for (const mapping of abi.mappings) {
    lines.push(...generateMappingType(mapping))
    lines.push('')
  }

  // Storage variable types
  for (const sv of abi.storageVariables) {
    lines.push(...generateStorageVariableType(sv))
    lines.push('')
  }

  // ABI constant + contract factory
  lines.push(...generateAbiConstant(abi))
  lines.push('')
  lines.push(...generateContractFactory(abi))
  lines.push('')

  return lines.join('\n')
}

// ── Struct generation ─────────────────────────────────────────────────

function generateStructInterface(struct: StructDef): string[] {
  const name = struct.path[struct.path.length - 1] ?? 'UnknownStruct'
  const lines: string[] = []

  lines.push(`export interface ${name} {`)

  for (const field of struct.fields) {
    const tsType = plaintextToTsType(field.type)
    lines.push(`  ${field.name}: ${tsType}`)
  }

  lines.push(`}`)
  return lines
}

// ── Record generation ─────────────────────────────────────────────────

function generateRecordInterface(record: RecordDef): string[] {
  const name = recordName(record)
  const lines: string[] = []

  lines.push(`export interface ${name} {`)
  lines.push(`  owner: string`)

  for (const field of record.fields) {
    if (field.name === 'owner') continue
    const tsType = plaintextToTsType(field.type)
    lines.push(`  ${field.name}: ${tsType}`)
  }

  lines.push(`}`)
  return lines
}

function generateRecordMapper(record: RecordDef): string[] {
  const name = recordName(record)
  const fnName = `to${name}`
  const lines: string[] = []

  lines.push(`export function ${fnName}(record: RecordValue): ${name} {`)
  lines.push(`  return {`)
  lines.push(`    owner: record.owner,`)

  for (const field of record.fields) {
    if (field.name === 'owner') continue
    const cast = plaintextToCast(field.type)
    lines.push(`    ${field.name}: record.fields.${field.name}?.value${cast} ?? ${plaintextDefault(field.type)},`)
  }

  lines.push(`  }`)
  lines.push(`}`)
  return lines
}

// ── Function input generation ─────────────────────────────────────────

function generateFunctionInputType(fn: AbiFunction, abi: ABI): string[] {
  const typeName = pascalCase(fn.name) + 'Inputs'
  const lines: string[] = []

  lines.push(`export type ${typeName} = {`)

  for (const input of fn.inputs) {
    const name = input.name ?? `arg${fn.inputs.indexOf(input)}`

    if (input.type.kind === 'plaintext') {
      const tsType = plaintextToTsType(input.type.type)
      lines.push(`  ${name}: ${tsType}`)
    } else if (input.type.kind === 'record') {
      const recName = input.type.path[input.type.path.length - 1] ?? 'RecordValue'
      const isLocal = !input.type.program || input.type.program === abi.program.replace('.aleo', '')
      lines.push(`  ${name}: ${isLocal ? recName : 'RecordValue'} | RecordValue | string`)
    } else if (input.type.kind === 'dynamicRecord') {
      lines.push(`  ${name}: RecordValue | string`)
    }
  }

  lines.push(`}`)
  return lines
}

// ── Function output generation ────────────────────────────────────────

function generateFunctionOutputType(fn: AbiFunction, abi: ABI): string[] {
  const typeName = pascalCase(fn.name) + 'Outputs'
  const lines: string[] = []

  // Filter out 'final' outputs since they're finalize handles, not user-facing data
  const dataOutputs = fn.outputs.filter((o) => o.type.kind !== 'final')

  if (dataOutputs.length === 0) {
    lines.push(`export type ${typeName} = void`)
    return lines
  }

  if (dataOutputs.length === 1) {
    const output = dataOutputs[0]
    const tsType = outputToTsType(output.type, abi)
    lines.push(`export type ${typeName} = ${tsType}`)
    return lines
  }

  // Multiple outputs — generate a tuple type
  const typeElements = dataOutputs.map((output) => outputToTsType(output.type, abi))

  lines.push(`export type ${typeName} = [${typeElements.join(', ')}]`)
  return lines
}

function outputToTsType(output: AbiFunction['outputs'][number]['type'], abi: ABI): string {
  if (output.kind === 'plaintext') {
    return plaintextToTsType(output.type)
  } else if (output.kind === 'record') {
    const recName = output.path[output.path.length - 1] ?? 'RecordValue'
    const isLocal = !output.program || output.program === abi.program.replace('.aleo', '')
    return isLocal ? recName : 'RecordValue'
  } else if (output.kind === 'dynamicRecord') {
    return 'RecordValue'
  } else if (output.kind === 'final') {
    return 'void'
  }
  return 'unknown'
}

// ── Mapping generation ────────────────────────────────────────────────

function generateMappingType(mapping: Mapping): string[] {
  const name = pascalCase(mapping.name)
  const keyType = plaintextToTsType(mapping.key)
  const valueType = plaintextToTsType(mapping.value)

  return [
    `export type ${name}MappingKey = ${keyType}`,
    `export type ${name}MappingValue = ${valueType}`,
  ]
}

// ── Storage variable generation ───────────────────────────────────────

function generateStorageVariableType(sv: StorageVariable): string[] {
  const name = pascalCase(sv.name)
  const tsType = storageTypeToTs(sv.type)

  return [`export type ${name}StorageType = ${tsType}`]
}

function storageTypeToTs(st: StorageType): string {
  if (st.kind === 'plaintext') {
    return plaintextToTsType(st.type)
  } else if (st.kind === 'vector') {
    return `${storageTypeToTs(st.element)}[]`
  }
  return 'unknown'
}

// ── Type mapping helpers ──────────────────────────────────────────────

function plaintextToTsType(pt: Plaintext): string {
  switch (pt.kind) {
    case 'primitive':
      return primitiveToTsType(pt.primitive)
    case 'array':
      return `${plaintextToTsType(pt.element)}[]`
    case 'struct':
      return pt.path[pt.path.length - 1] ?? 'unknown'
    case 'optional':
      return `${plaintextToTsType(pt.inner)} | undefined`
    default:
      return 'unknown'
  }
}

function primitiveToTsType(p: Primitive): string {
  switch (p) {
    case 'address':
    case 'field':
    case 'group':
    case 'scalar':
    case 'signature':
    case 'identifier':
      return 'string'
    case 'boolean':
      return 'boolean'
    case 'u8':
    case 'u16':
    case 'u32':
    case 'i8':
    case 'i16':
    case 'i32':
      return 'number'
    case 'u64':
    case 'u128':
    case 'i64':
    case 'i128':
      return 'bigint'
    default:
      return 'unknown'
  }
}

function plaintextToCast(pt: Plaintext): string {
  if (pt.kind !== 'primitive') return ''
  switch (pt.primitive) {
    case 'u8':
    case 'u16':
    case 'u32':
    case 'i8':
    case 'i16':
    case 'i32':
      return ' as number'
    case 'u64':
    case 'u128':
    case 'i64':
    case 'i128':
      return ' as bigint'
    case 'field':
    case 'group':
    case 'scalar':
      return ' as string'
    case 'address':
    case 'signature':
    case 'identifier':
      return ' as string'
    case 'boolean':
      return ' as boolean'
    default:
      return ''
  }
}

function plaintextDefault(pt: Plaintext): string {
  if (pt.kind !== 'primitive') return "''"
  switch (pt.primitive) {
    case 'boolean':
      return 'false'
    case 'u8': case 'u16': case 'u32':
    case 'i8': case 'i16': case 'i32':
      return '0'
    case 'u64': case 'u128':
    case 'i64': case 'i128':
      return '0n'
    case 'field': case 'group': case 'scalar':
      return "''"
    case 'address': case 'signature': case 'identifier':
      return "''"
    default:
      return "''"
  }
}

// ── ABI constant + contract factory ───────────────────────────────────

function generateAbiConstant(abi: ABI): string[] {
  // Embed the already-parsed ABI as a typed constant.
  // This avoids a round-trip through parseAbi at runtime.
  return [
    `/** The parsed ABI for ${abi.program}. */`,
    `export const PROGRAM_ABI: ABI = ${JSON.stringify(abi, null, 2)}`,
  ]
}

function generateContractFactory(abi: ABI): string[] {
  const programName = abi.program
  const factoryName = pascalCase(programName.replace('.aleo', ''))
  const lines: string[] = []

  // Generate typed interface with explicit method names
  lines.push(`export interface ${factoryName}Contract {`)
  lines.push(`  program: string`)
  lines.push(`  abi: ABI | undefined`)

  // read methods — one per mapping
  if (abi.mappings.length > 0) {
    lines.push(`  read: {`)
    for (const mapping of abi.mappings) {
      const keyType = plaintextToTsType(mapping.key)
      lines.push(`    ${mapping.name}: (params: { key: ${keyType} }) => Promise<unknown>`)
    }
    lines.push(`  }`)
  } else {
    lines.push(`  read: Record<string, (params: { key: string }) => Promise<unknown>>`)
  }

  // write methods — one per function
  if (abi.functions.length > 0) {
    lines.push(`  write: {`)
    for (const fn of abi.functions) {
      lines.push(`    ${fn.name}: (params: { inputs: string[]; fee?: bigint }) => Promise<string>`)
    }
    lines.push(`  }`)
  }

  // simulate methods — one per function
  if (abi.functions.length > 0) {
    lines.push(`  simulate: {`)
    for (const fn of abi.functions) {
      lines.push(`    ${fn.name}: (params: { inputs: string[] }) => Promise<RawSimulateResult>`)
    }
    lines.push(`  }`)
  }

  // execute methods — one per function
  if (abi.functions.length > 0) {
    lines.push(`  execute: {`)
    for (const fn of abi.functions) {
      lines.push(`    ${fn.name}: (params: { inputs: string[]; fee?: bigint }) => Promise<RawExecuteResult>`)
    }
    lines.push(`  }`)
  }

  lines.push(`  fetchAbi: () => Promise<ReturnType<typeof parseAbi>>`)
  lines.push(`}`)
  lines.push('')

  // Generate factory function
  lines.push(`/**`)
  lines.push(` * Creates a typed contract instance for ${programName}.`)
  lines.push(` * Provides autocomplete for all function and mapping names.`)
  lines.push(` */`)
  lines.push(`export function create${factoryName}Contract(options: {`)
  lines.push(`  publicClient?: PublicClient,`)
  lines.push(`  walletClient?: WalletClient,`)
  lines.push(`  programSource?: string,`)
  lines.push(`  imports?: Record<string, string>,`)
  lines.push(`}): ${factoryName}Contract {`)
  lines.push(`  const client = options.publicClient && options.walletClient`)
  lines.push(`    ? { public: options.publicClient, wallet: options.walletClient }`)
  lines.push(`    : options.publicClient ?? options.walletClient!`)
  lines.push(`  return getContract({ program: PROGRAM_ID, abi: PROGRAM_ABI, client, programSource: options.programSource, imports: options.imports }) as unknown as ${factoryName}Contract`)
  lines.push(`}`)

  return lines
}

// ── Utility ───────────────────────────────────────────────────────────

function recordName(record: RecordDef): string {
  return record.path[record.path.length - 1] ?? 'UnknownRecord'
}

function pascalCase(s: string): string {
  return s
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}
